plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.4
  DisplayCopNames: true
  DisabledByDefault: true

Layout/LineLength:
  Max: 120

Layout/DotPosition:
  EnforcedStyle: leading

Layout/HashAlignment:
  Enabled: true

Layout/ExtraSpacing:
  AllowForAlignment: false

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%i': '[]'
    '%q': '{}'
    '%Q': '{}'
    '%r': '{}'
    '%s': '[]'
    '%w': '[]'
    '%W': '[]'
    '%x': '[]'

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/SpaceInsideBlockBraces:
  EnforcedStyleForEmptyBraces: space

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/ClassAndModuleChildren:
  EnforcedStyle: nested
